.PHONY: clean All

All:
	@echo "----------Building project:[ vkti - Debug ]----------"
	@$(MAKE) -f  "vkti.mk"
clean:
	@echo "----------Cleaning project:[ vkti - Debug ]----------"
	@$(MAKE) -f  "vkti.mk" clean
